import type { Report } from "../types/report";

// Builds a clean, WhatsApp-friendly plain-text summary of the report.
export function buildShareText(report: Report): string {
  const lines: string[] = [];
  lines.push("🩺 MediReport AI — Lab Report Summary");
  if (report.patientName) {
    lines.push(`Patient: ${report.patientName}${report.patientAge ? `, Age ${report.patientAge}` : ""}`);
  }
  lines.push("");
  lines.push(report.summary);

  const flagged = report.markers.filter((m) => m.status !== "normal");
  if (flagged.length > 0) {
    lines.push("");
    lines.push("⚠️ Needs attention:");
    for (const m of flagged) {
      lines.push(
        `• ${m.name}: ${m.value} ${m.unit} (normal ${m.refRange}) — ${m.status}`
      );
    }
  }

  const normalCount = report.markers.length - flagged.length;
  if (normalCount > 0) {
    lines.push("");
    lines.push(`✅ ${normalCount} other marker(s) in the normal range.`);
  }

  lines.push("");
  lines.push("Not a medical diagnosis. Please consult a doctor.");
  lines.push("— Shared via MediReport AI");
  return lines.join("\n");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// A clean printable one-pager — also serves as a doctor-visit sheet. Opened in a
// new window so it can be saved as PDF without affecting the app's layout.
function buildPrintableHtml(report: Report): string {
  const flagged = report.markers.filter((m) => m.status !== "normal");
  const today = new Date().toLocaleDateString();

  const markerBlocks = flagged
    .map((m) => {
      const questions = m.doctorQuestions.length
        ? `<div class="q"><strong>Ask your doctor:</strong><ul>${m.doctorQuestions
            .map((q) => `<li>${escapeHtml(q)}</li>`)
            .join("")}</ul></div>`
        : "";
      return `<div class="marker">
        <div class="mhead"><span class="mname">${escapeHtml(m.name)}</span>
        <span class="mstatus ${m.status}">${m.status.toUpperCase()}</span></div>
        <div class="mval">${escapeHtml(m.value)} ${escapeHtml(m.unit)} · normal ${escapeHtml(m.refRange)}</div>
        <p>${escapeHtml(m.plainExplanation)}</p>${questions}
      </div>`;
    })
    .join("");

  const patient = report.patientName
    ? `<p class="patient">${escapeHtml(report.patientName)}${report.patientAge ? `, Age ${escapeHtml(report.patientAge)}` : ""}</p>`
    : "";

  return `<!doctype html><html><head><meta charset="utf-8"><title>MediReport Summary</title>
  <style>
    body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;color:#1f2937;max-width:720px;margin:32px auto;padding:0 20px;line-height:1.5}
    h1{font-size:20px;margin:0 0 2px}
    .sub{color:#6b7280;font-size:13px;margin:0 0 16px}
    .patient{font-weight:600;margin:0 0 12px}
    .summary{background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:12px 14px;margin-bottom:18px}
    h2{font-size:14px;text-transform:uppercase;letter-spacing:.04em;color:#6b7280;margin:20px 0 8px}
    .marker{border:1px solid #e5e7eb;border-radius:10px;padding:12px 14px;margin-bottom:10px}
    .mhead{display:flex;justify-content:space-between;align-items:center}
    .mname{font-weight:600}
    .mstatus{font-size:11px;font-weight:700;padding:2px 8px;border-radius:999px}
    .mstatus.low{background:#fef3c7;color:#92400e}.mstatus.high{background:#fee2e2;color:#991b1b}
    .mval{color:#6b7280;font-size:13px;margin:2px 0 6px}
    .q{margin-top:6px;font-size:13px}.q ul{margin:4px 0 0 18px}
    .disc{color:#9ca3af;font-size:11px;margin-top:20px;border-top:1px solid #e5e7eb;padding-top:10px}
  </style></head><body>
    <h1>MediReport AI — Lab Report Summary</h1>
    <p class="sub">Generated ${today}</p>
    ${patient}
    <div class="summary">${escapeHtml(report.summary)}</div>
    ${flagged.length ? `<h2>Needs attention (${flagged.length})</h2>${markerBlocks}` : ""}
    <p class="sub">${report.markers.length - flagged.length} other marker(s) in the normal range.</p>
    <p class="disc">This is not a medical diagnosis. Please consult a doctor for interpretation and treatment. Generated by MediReport AI.</p>
  </body></html>`;
}

export function printSummary(report: Report): void {
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(buildPrintableHtml(report));
  win.document.close();
  win.focus();
  // Give the new document a tick to render before invoking print.
  setTimeout(() => win.print(), 250);
}

export function shareOnWhatsApp(report: Report): void {
  const text = encodeURIComponent(buildShareText(report));
  window.open(`https://wa.me/?text=${text}`, "_blank", "noopener");
}

// Uses the native share sheet when available (great on mobile), else copies to
// clipboard. Returns "shared" | "copied" | "failed" so the UI can react.
export async function shareNative(
  report: Report
): Promise<"shared" | "copied" | "failed"> {
  const text = buildShareText(report);
  const nav = navigator as Navigator & {
    share?: (data: { text: string; title?: string }) => Promise<void>;
  };
  try {
    if (nav.share) {
      await nav.share({ title: "MediReport AI — Lab Report Summary", text });
      return "shared";
    }
    await navigator.clipboard.writeText(text);
    return "copied";
  } catch {
    return "failed";
  }
}
